### ISSUE TITLE
Some DF reputations do not stay hidden

### ISSUE THREAD

**Issue by Slackluster** [teelolws/InactiveReputationHeaders#13]
These are reputations I've hidden before:
![image](https://github.com/user-attachments/assets/da390a4e-b520-4143-9405-033ba9e1a13d)

They stay hidden for some time. This is in-between relogs, reloads, rep gains and such. But at some point, they seem to unhide themselves. They don't seem to exist anymore in my char-specific SavedVars either:
```
IRH_DB = {
[1052] = true,
[1272] = true,
[1444] = true,
[2507] = true,
[1302] = true,
[1162] = true,
[2510] = true,
[980] = true,
}
```

I am not sure what is causing this yet, but I'm trying to reproduce it.

**Comment by teelolws** [comment]
Those reputations are all supposed to be hideable using the base UI. But since making them account-wide, Blizzard have broken them, somehow. They will randomly disappear off your reputation list completely, then won't reappear until you talk to an NPC from their faction or do something that earns/loses rep with them. When it comes back, its Inactive flag is unset.

I'm not sure whats causing it either. Logging onto an alt that hasn't unlocked Dragonflight, maybe? I'll give Blizzard some time to fix it themselves. If they don't within a reasonable amount of time, I'll look at an override.

**Comment by Slackluster** [comment]
That's reasonable yeah, a lot of stuff is out of whack at the moment and it wouldn't surprise me this is similar to other bugs related to the new UI, settings, etc. Thanks for the response! o7
